### ISSUE TITLE
Is this example already support async action?

### ISSUE THREAD

**Issue by kiddo13** [NSLS/universal-webpack-boilerplate#3]
I just starting to use universal-webpack for server side rendering.
For async action, I use [redux-connect](https://github.com/makeomatic/redux-connect) component.
But in this example, I don't see any usage of such component.

So how do you handle async action in this example?

**Comment by ignatevdev** [comment]
Hi.
Async actions should be handled this way:

Action:
```
export function fetchStuff() {
    return {
        types: [START_LOAD, FETCH_STUFF_SUCCESS, LOAD_FAIL],
        promise: client => client.get( '/stuff')
    };
}
```

`types` is an array of 3 action types. Action with the first type fires on request start, second - on successful response, third - on unsuccessful response.

`promise` is a function which takes the API class as a first argument and should return a promise (in most cases a request). This class is located in `/src/core/hepers/ApiClient.js`. It's very simple, but just in case you wonder how to POST some data in your action, here is how it would look like

```
return {
    types: [START_LOAD, FETCH_STUFF_SUCCESS, LOAD_FAIL],
    promise: client => client.post( '/stuff', {data: {message: 'hi'})
};
```


Component:

```
@asyncConnect(
	[{
		promise: ({store: {dispatch, getState}, params}) => {
			const promises = [];

			promises.push(fetchStuff());

			return Promise.all(promises.map(f => dispatch(f)));
		}
	}]
)

export default class App extends Component {
...
```

**Comment by ignatevdev** [comment]
Actually, I just realised that I totally forgot about this boilerplate having a react-router 4, because in my other projects I didn't risk migrating to it and stood with the 3rd version, which works well with the redux-connect. However, this method wouldn't work here, so my previous comment makes no sense. I will take some more time to figure out the best way for async preloading and post my results here.

**Comment by ignatevdev** [comment]
@kiddo13 After some research I found out that with the latest React-router API there is basically no way to implement the same behaviour that AsyncConnect was providing because there is no longer a centralized router config. Therefore, I've decided to rollback this boilerplate to React-router 3 and reconfigured `redux-connect`. Therefore, you could now rely on the old router's api and fetch your data with asyncConnect().
