### ISSUE TITLE
React Router v4

### ISSUE THREAD

**Issue by Iuriy-Budnikov** [NSLS/universal-webpack-boilerplate#6]
Hey guys, 

Do you have an example for v4  ? :)

**Comment by ignatevdev** [comment]
Hi.
The project was initially based on v4 while it was in beta, but I intentionally downgraded it to v3, because I found RR4 core ideas too raw and half-baked. Doing things like server-side data preloading, global pending state (which means, that while the next page is fetching data on the client, the previous page is still shown, avoiding preloaders and so on) and some other important things for production-ready application are not there yet and might not be coming at all because of the concept of the library. 

You can refer to [this](https://github.com/NSLS/universal-webpack-boilerplate/tree/ca6cafa3c430594177cbdfdff7dfec5061f18d3e) version for some understanding on how the project should look like with v4, but it would probably not work without tweaking it for the latest version, because the syntax might have changed.

But if I were you, I would better stick to v3

**Comment by Iuriy-Budnikov** [comment]
Thanks so much.
